ficha = input("elija su ficha(x,o): ")

if ficha == "x":
    print("jugador(x):")
    print("   1 2 3")
    print(" a| | | ")
    print("  --+-+-")
    print(" b| | | ")
    print("  --+-+-")
    print(" c| | | ")
    posnum = int(input("ingrese la numero de posición: "))
    poslet = input("ingrese la letra de posición: ")
    if posnum == 1 and poslet == "a":
        print("jugador(o):")
        print("   1 2 3")
        print(" a|x| | |")
        print("  |-+-+-|")
        print(" b| | | |")
        print("  |-+-+-|")
        print(" c| | | |")
        posnum2 = int(input("ingrese la numero de posición: "))
        poslet2 = input("ingrese la letra de posición: ")
        if posnum2 == 1 and poslet2 == "b":
            print("jugador(x):")
            print("   1 2 3")
            print(" a|x| | |")
            print("  |-+-+-|")
            print(" b|o| | |")
            print("  |-+-+-|")
            print(" c| | | |")
            posnum3 = int(input("ingrese la numero de posición: "))
            poslet3 = input("ingrese la letra de posición: ")
            if posnum3 == 1 and poslet3 == "c":
                print("jugador(o):")
                print("   1 2 3")
                print(" a|x| | |")
                print("  |-+-+-|")
                print(" b|o| | |")
                print("  |-+-+-|")
                print(" c|x| | |")
                posnum4 = int(input("ingrese la numero de posición: "))
                poslet4 = input("ingrese la letra de posición: ")
                if posnum4 == 2 and poslet4 == "a":
                    print("jugador(x):")
                    print("   1 2 3")
                    print(" a|x|o| |")
                    print("  |-+-+-|")
                    print(" b|o| | |")
                    print("  |-+-+-|")
                    print(" c|x| | |")
                    posnum5 = int(input("ingrese la numero de posición: "))
                    poslet5 = input("ingrese la letra de posición: ")
                    if posnum5 == 2  and poslet5 == "b":
                        print("jugador(o):")
                        print("   1 2 3")
                        print(" a|x|o| |")
                        print("  |-+-+-|")
                        print(" b|o|x| |")
                        print("  |-+-+-|")
                        print(" c|x| | |")
                        posnum6 = int(input("ingrese la numero de posición: "))
                        poslet6 = input("ingrese la letra de posición: ")
                        if posnum6 == 2 and poslet6 == "c":
                            print("jugador(x):")
                            print(" a|x|o| |")
                            print("  |-+-+-|")
                            print(" b|o|x| |")
                            print("  |-+-+-|")
                            print(" c|x|o| |")
                            posnum7 = int(input("ingrese la numero de posición: "))
                            poslet7 = input("ingrese la letra de posición: ")
                            if posnum7 == 3 and poslet7 == "a":
                                print("jugador(o):")
                                print("   1 2 3")
                                print(" a|x|o|x|")
                                print("  |-+-+-|")
                                print(" b|o|x| |")
                                print("  |-+-+-|")
                                print(" c|x|o| |")
                                posnum7 = int(input("ingrese la numero de posición: "))
                                poslet7 = input("ingrese la letra de posición: ")
                                if posnum7 == 3 and poslet7 == "b":
                                    print("jugador(x):")
                                    print("   1 2 3")
                                    print(" a|x|o|x|")
                                    print("  |-+-+-|")
                                    print(" b|o|x|o|")
                                    print("  |-+-+-|")
                                    print(" c|x|o| |")
                                    posnum8 = int(input("ingrese la numero de posición: "))
                                    poslet8 = input("ingrese la letra de posición: ")
                                    if posnum8 == 3 and poslet8 == "c":
                                        print("   1 2 3")
                                        print(" a|x|o|x|")
                                        print("  |-+-+-|")
                                        print(" b|o|x|o|")
                                        print("  |-+-+-|")
                                        print(" c|x|o|x|")
                                        print("es un empate")
    if posnum == 1 and poslet == "b": 
        print("jugador(o):")
        print("   1 2 3")
        print(" a| | | ")
        print("  |-+-+-")
        print(" b|x| | ")
        print("  |-+-+-")
        print(" c| | | ")
        posnum2 =int(input("ingrese la numero de posición: "))
        poslet2 =input("ingrese la letra de posición: ")
        if posnum2 == 1 and poslet2 == "a":
            print("jugador(x):")
            print("   1 2 3")
            print(" a|o| | ")
            print("  |-+-+-")
            print(" b|x| | ")
            print("  |-+-+-")
            print(" c| | | ")
            posnum3 =int(input("ingrese la numero de posición: "))
            poslet3 =input("ingrese la letra de posición: ")
            if posnum3 == 1 and poslet3 == "c":
                print("jugador(o):")
                print("   1 2 3")
                print(" a|o| | ")
                print("  |-+-+-")
                print(" b|x| | ")
                print("  |-+-+-")
                print(" c|x| | ")
                posnum4 =int(input("ingrese la numero de posición: "))
                poslet4 =input("ingrese la letra de posición: ")
                if posnum4 == 2 and poslet4 == "a":
                    print("jugador(x):")
                    print("   1 2 3")
                    print(" a|o|o| ")
                    print("  |-+-+-")
                    print(" b|x| | ")
                    print("  |-+-+-")
                    print(" c|x| | ")
                    posnum5 =int(input("ingrese la numero de posición: "))
                    poslet5 =input("ingrese la letra de posición: ")
                    if posnum5 == 2 and poslet5 == "b":
                        print("jugador(o):")
                        print("   1 2 3")
                        print(" a|o|o| ")
                        print("  |-+-+-")
                        print(" b|x|x| ")
                        print("  |-+-+-")
                        print(" c|x| | ")
                        posnum6 =int(input("ingrese la numero de posición: "))
                        poslet6 =input("ingrese la letra de posición: ")
                        if posnum6 == 2 and poslet6 == "c":
                            print("jugador(x):")
                            print("   1 2 3")
                            print(" a|o|o| ")
                            print("  |-+-+-")
                            print(" b|x|x| ")
                            print("  |-+-+-")
                            print(" c|x|o| ")
                            posnum7 =int(input("ingrese la numero de posición: "))
                            poslet7 =input("ingrese la letra de posición: ")
                            if posnum7 == 3 and poslet7 == "a":
                                print("jugador(o):")
                                print("   1 2 3")
                                print(" a|o|o|x")
                                print("  |-+-+-")
                                print(" b|x|x| ")
                                print("  |-+-+-")
                                print(" c|x|o| ")
                                posnum8 =int(input("ingrese la numero de posición: "))
                                poslet8 =input("ingrese la letra de posición: ")
                                if posnum8 == 3 and poslet8 == "b":
                                    print("jugador(x):")
                                    print("   1 2 3")
                                    print(" a|o|o|x")
                                    print("  |-+-+-")
                                    print(" b|x|x|o")
                                    print("  |-+-+-")
                                    print(" c|x|o| ")
                                    posnum9 =int(input("ingrese la numero de posición: "))
                                    poslet9 =input("ingrese la letra de posición: ")
                                    if posnum9 == 3 and poslet9 == "c"
                                        print("   1 2 3")
                                        print(" a|o|o|x")
                                        print("  |-+-+-")
                                        print(" b|x|x|o")
                                        print("  |-+-+-")
                                        print(" c|x|o|x")
                                        print("es un empate")
    if posnum == 1 and poslet == "c": 
        print("jugador(o):")
        print("   1 2 3")
        print(" a| | | ")
        print("  |-+-+-")
        print(" b| | | ")
        print("  |-+-+-")
        print(" c|x| | ")
        posnum2 =int(input("ingrese la numero de posición: "))
        poslet2 =input("ingrese la letra de posición: ")
    if posnum == 2 and poslet == "a": 
        print("jugador(o):")
        print("   1 2 3")
        print(" a| |x| ")
        print("  |-+-+-")
        print(" b| | | ")
        print("  |-+-+-")
        print(" c| | | ")
        posnum2 =int(input("ingrese la numero de posición: "))
        poslet2 =input("ingrese la letra de posición: ")
    if posnum == 2 and poslet == "b": 
        print("jugador(o):")
        print("   1 2 3")
        print(" a| | | ")
        print("  |-+-+-")
        print(" b| |x| ")
        print("  |-+-+-")
        print(" c| | | ")
        posnum2 =int(input("ingrese la numero de posición: "))
        poslet2 =input("ingrese la letra de posición: ")
    if posnum == 2 and poslet == "c": 
        print("jugador(o):")
        print("   1 2 3")
        print(" a| | | ")
        print("  |-+-+-")
        print(" b| | | ")
        print("  |-+-+-")
        print(" c| |x| ")
        posnum2 =int(input("ingrese la numero de posición: "))
        poslet2 =input("ingrese la letra de posición: ")
    if posnum == 3 and poslet == "a": 
        print("jugador(o):")
        print("   1 2 3")
        print(" a| | |x")
        print("  |-+-+-")
        print(" b| | | ")
        print("  |-+-+-")
        print(" c| | | ")
        posnum2 =int(input("ingrese la numero de posición: "))
        poslet2 =input("ingrese la letra de posición: ")
    if posnum == 3 and poslet == "b": 
        print("jugador(o):")
        print("   1 2 3")
        print(" a| | | ")
        print("  |-+-+-")
        print(" b| | |x")
        print("  |-+-+-")
        print(" c| | | ")
        posnum2 =int(input("ingrese la numero de posición: "))
        poslet2 =input("ingrese la letra de posición: ")
    if posnum == 3 and poslet == "c": 
        print("jugador(o):")
        print("   1 2 3")
        print(" a| | | ")
        print("  |-+-+-")
        print(" b|x| | ")
        print("  |-+-+-")
        print(" c| | | ")
        posnum2 =int(input("ingrese la numero de posición: "))
        poslet2 =input("ingrese la letra de posición: ")
if ficha == "o":
    print("jugador1:")
    print("  1 2 3")
    print(" a | | ")
    print("  -+-+-")
    print(" b | | ")
    print("  -+-+-")
    print(" c | | ")
    posnum =int(input("ingrese la numero de posición: "))
    poslet =input("ingrese la letra de posición: ")
    if posnum == 1 and poslet == "a":
        print("jugador2:")
        print("   1 2 3")
        print(" a|o| | |")
        print("  |-+-+-|")
        print(" b| | | |")
        print("  |-+-+-|")
        print(" c| | | |")
        posnum2 = int(input("ingrese la numero de posición: "))
        poslet2 = input("ingrese la letra de posición: ")
    if posnum == 1  and poslet == "b":
        print("jugador2:")
        print("   1 2 3")
        print(" a| | | ")
        print("   -+-+-")
        print(" b|o| | ")
        print("   -+-+-")
        print(" c| | | ")
        posnum2 =int(input("ingrese la numero de posición: "))
        poslet2 =input("ingrese la letra de posición: ")
    if posnum == 1  and poslet == "c":
        print("jugado2:")
        print("   1 2 3")
        print(" a| | | ")
        print("   -+-+-")
        print(" b| | | ")
        print("   -+-+-")
        print(" c|o| | ")
        posnum2 =int(input("ingrese la numero de posición: "))
        poslet2 =input("ingrese la letra de posición: ")
    if posnum == 2  and poslet == "a":
        print("jugador2:")
        print("   1 2 3")
        print(" a| |o| ")
        print("   -+-+-")
        print(" b| | | ")
        print("   -+-+-")
        print(" c| | | ")
        posnum2 = int(input("ingrese la numero de posición"))
        poslet2 = input("ingrese la letra de posición")
    if posnum == 2 and poslet == "b":
        print("jugador2:")
        print("   1 2 3")
        print(" a| | | ")
        print("   -+-+-")
        print(" b| |o| ")
        print("   -+-+-")
        print(" c| | | ")
        posnum2 =int(input("ingrese la numero de posición: "))
        poslet2 =input("ingrese la letra de posición: ")
    if posnum == 2 and poslet == "c":
        print("jugado2:")
        print("   1 2 3")
        print(" a| | | ")
        print("   -+-+-")
        print(" b| | | ")
        print("   -+-+-")
        print(" c| |o| ")
        posnum2 =int(input("ingrese la numero de posición: "))
        poslet2 =input("ingrese la letra de posición: ")
    if posnum == 3 and poslet == "a":
        print("jugador2:")
        print("   1 2 3")
        print(" a| | |o")
        print("   -+-+-")
        print(" b| | | ")
        print("   -+-+-")
        print(" c| | | ")
        posnum2 = int(input("ingrese la numero de posición: "))
        poslet2 = input("ingrese la letra de posición: ")
    if posnum == 3 and poslet == "b":
        print("jugador2:")
        print("   1 2 3")
        print(" a| | | ")
        print("   -+-+-")
        print(" b| | |o")
        print("   -+-+-")
        print(" c| | | ")
        posnum2 =int(input("ingrese la numero de posición: "))
        poslet2 =input("ingrese la letra de posición: ")
    if posnum == 3 and poslet == "c":
        print("jugado2:")
        print("   1 2 3")
        print(" a| | | ")
        print("   -+-+-")
        print(" b| | | ")
        print("   -+-+-")
        print(" c| | |o")
        posnum2 =int(input("ingrese la numero de posición: "))
        poslet2 =input("ingrese la letra de posición: ")
